name: Docker Generate LF-Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout this repo
      uses: actions/checkout@v2
      run: docker run -v /VER_GEN:/tmp ubuntu ./tmp/get_current_version.sh


