name: Docker Generate LF-Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Checkout this repo
      run: cd $GITHUB_WORKSPACE && ls
      
    - name: Analyze Laserfiche Installer
      run: cd $GITHUB_WORKSPACE/VER_GEN && bash get_current_version.sh

    - name: Show results
      run: cd $GITHUB_WORKSPACE/VER_GEN && cat current_version.json
      