name: Docker Generate LF-Versions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Checkout this repo
      run: cd $GITHUB_WORKSPACE && ls
      
    - name: Analyze Laserfiche Installer
      run: cd $GITHUB_WORKSPACE/VER_GEN && bash get_current_version.sh

    - name: Show Version Info
      run: cd $GITHUB_WORKSPACE/VER_GEN && cat current_version.json

    - name: Commit Version updates to main
      run: git config --global user.email ${GH_EMAIL} && git config --global user.name ${GH_USER} && git add -f $GITHUB_WORKSPACE/VER_GEN/current_version.json && git commit -m "GitHub action updated current_version.json info" && git push
      env:
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
        GH_USER: ${{ secrets.GH_USER }}